# Generated by Django 4.2.5 on 2023-10-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_delivery_point_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offices', to='order.offices'),
        ),
    ]
