# Generated by Django 4.2.5 on 2023-10-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_start_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver', to='order.deliver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('on_work', 'on_work'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderer', to='order.orderer'),
        ),
    ]
