# Generated by Django 4.2.5 on 2023-10-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_street_city_alter_delivery_point_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street',
            old_name='city',
            new_name='city_street',
        ),
    ]
