# Generated by Django 4.2.5 on 2023-10-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_city_street_street_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_point',
            name='name',
            field=models.CharField(blank=True, default='noname', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery_point',
            name='street',
            field=models.CharField(blank=True, choices=[('Сумская', 'Сумская'), ('Гагарина проспект', 'Гагарина проспект'), ('Пушкинская', 'Пушкинская'), ('Одесская', 'Одесская')], max_length=100),
        ),
        migrations.AlterField(
            model_name='offices',
            name='name',
            field=models.CharField(blank=True, default='noname', max_length=100),
        ),
        migrations.AlterField(
            model_name='offices',
            name='street',
            field=models.CharField(blank=True, choices=[('Сумская', 'Сумская'), ('Гагарина проспект', 'Гагарина проспект'), ('Пушкинская', 'Пушкинская'), ('Одесская', 'Одесская')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_point',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offices', to='order.offices'),
        ),
    ]
