# Generated by Django 4.2.5 on 2023-10-09 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_date_on_work_alter_delivery_point_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_fihished',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_on_work',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 15, 15, 56, 437788)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('waiting', 'waiting'), ('on_work', 'on_work'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=20),
        ),
    ]
