# Generated by Django 4.2.5 on 2023-10-09 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_date_fihished_alter_order_date_on_work_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_fihished',
            new_name='date_finished',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_on_work',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 15, 17, 39, 314820)),
        ),
    ]
