# Generated by Django 4.2.5 on 2023-10-12 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_date_fihished_order_date_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_point',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Киев', 'Киев')], max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery_point',
            name='street',
            field=models.CharField(blank=True, choices=[('Сумская', 'Сумская'), ('Гагарина проспект', 'Гагарина проспект'), ('Пушкинская', 'Пушкинская'), ('Одесская', 'Одесская'), ('Владимирская', 'Владимирская'), ('Гагарина проспект', 'Гагарина проспект')], max_length=100),
        ),
        migrations.AlterField(
            model_name='offices',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Киев', 'Киев')], max_length=100),
        ),
        migrations.AlterField(
            model_name='offices',
            name='street',
            field=models.CharField(blank=True, choices=[('Сумская', 'Сумская'), ('Гагарина проспект', 'Гагарина проспект'), ('Пушкинская', 'Пушкинская'), ('Одесская', 'Одесская'), ('Владимирская', 'Владимирская'), ('Гагарина проспект', 'Гагарина проспект')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_on_work',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 14, 56, 561573)),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Киев', 'Киев')], max_length=100, null=True),
        ),
    ]
