# Generated by Django 4.2.5 on 2023-10-14 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_date_on_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_on_work',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 10, 39, 11, 100524)),
        ),
    ]
